package net.favor.imagecapter.hibernate.reveng.pojo;

// Generated Aug 7, 2013 11:29:02 PM by Hibernate Tools 3.4.0.CR1

/**
 * CodUser generated by hbm2java
 */
public class CodUser implements java.io.Serializable {

	private String cuKey;
	private String cuUsername;

	public CodUser() {
	}

	public CodUser(String cuKey, String cuUsername) {
		this.cuKey = cuKey;
		this.cuUsername = cuUsername;
	}

	public String getCuKey() {
		return this.cuKey;
	}

	public void setCuKey(String cuKey) {
		this.cuKey = cuKey;
	}

	public String getCuUsername() {
		return this.cuUsername;
	}

	public void setCuUsername(String cuUsername) {
		this.cuUsername = cuUsername;
	}

}
