package net.favor.imagecapter.hibernate.reveng.pojo;

// Generated Aug 7, 2013 11:29:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ImageAccessHist generated by hbm2java
 */
public class ImageAccessHist implements java.io.Serializable {

	private Integer iaKey;
	private Character iaAccessType;
	private String iaCreatedBy;
	private Date iaCreatedDate;
	private Integer iaImgKey;

	public ImageAccessHist() {
	}

	public ImageAccessHist(Character iaAccessType, String iaCreatedBy, Date iaCreatedDate, Integer iaImgKey) {
		this.iaAccessType = iaAccessType;
		this.iaCreatedBy = iaCreatedBy;
		this.iaCreatedDate = iaCreatedDate;
		this.iaImgKey = iaImgKey;
	}

	public Integer getIaKey() {
		return this.iaKey;
	}

	public void setIaKey(Integer iaKey) {
		this.iaKey = iaKey;
	}

	public Character getIaAccessType() {
		return this.iaAccessType;
	}

	public void setIaAccessType(Character iaAccessType) {
		this.iaAccessType = iaAccessType;
	}

	public String getIaCreatedBy() {
		return this.iaCreatedBy;
	}

	public void setIaCreatedBy(String iaCreatedBy) {
		this.iaCreatedBy = iaCreatedBy;
	}

	public Date getIaCreatedDate() {
		return this.iaCreatedDate;
	}

	public void setIaCreatedDate(Date iaCreatedDate) {
		this.iaCreatedDate = iaCreatedDate;
	}

	public Integer getIaImgKey() {
		return this.iaImgKey;
	}

	public void setIaImgKey(Integer iaImgKey) {
		this.iaImgKey = iaImgKey;
	}

}
