package net.favor.imagecapter.hibernate.reveng.pojo;

// Generated Aug 7, 2013 11:29:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ImageRecord generated by hbm2java
 */
public class ImageRecord implements java.io.Serializable {

	private Integer imImageKey;
	private String imFileName;
	private Integer imFileSize;
	private String imCreatedBy;
	private Date imCreatedDate;
	private String imUpdatedBy;
	private Date imUpdatedDate;
	private String imComment;
	private Date imCaptureTime;
	private Date imCaptureDate;
	private String imCameraMake;
	private String imCameraModel;
	private Double imFocal;
	private Double imAperature;
	private Double imExposure;
	private String imIso;

	public ImageRecord() {
	}

	public ImageRecord(String imFileName, Integer imFileSize, String imCreatedBy, Date imCreatedDate,
			String imUpdatedBy, Date imUpdatedDate, String imComment, Date imCaptureTime, Date imCaptureDate,
			String imCameraMake, String imCameraModel, Double imFocal, Double imAperature, Double imExposure,
			String imIso) {
		this.imFileName = imFileName;
		this.imFileSize = imFileSize;
		this.imCreatedBy = imCreatedBy;
		this.imCreatedDate = imCreatedDate;
		this.imUpdatedBy = imUpdatedBy;
		this.imUpdatedDate = imUpdatedDate;
		this.imComment = imComment;
		this.imCaptureTime = imCaptureTime;
		this.imCaptureDate = imCaptureDate;
		this.imCameraMake = imCameraMake;
		this.imCameraModel = imCameraModel;
		this.imFocal = imFocal;
		this.imAperature = imAperature;
		this.imExposure = imExposure;
		this.imIso = imIso;
	}

	public Integer getImImageKey() {
		return this.imImageKey;
	}

	public void setImImageKey(Integer imImageKey) {
		this.imImageKey = imImageKey;
	}

	public String getImFileName() {
		return this.imFileName;
	}

	public void setImFileName(String imFileName) {
		this.imFileName = imFileName;
	}

	public Integer getImFileSize() {
		return this.imFileSize;
	}

	public void setImFileSize(Integer imFileSize) {
		this.imFileSize = imFileSize;
	}

	public String getImCreatedBy() {
		return this.imCreatedBy;
	}

	public void setImCreatedBy(String imCreatedBy) {
		this.imCreatedBy = imCreatedBy;
	}

	public Date getImCreatedDate() {
		return this.imCreatedDate;
	}

	public void setImCreatedDate(Date imCreatedDate) {
		this.imCreatedDate = imCreatedDate;
	}

	public String getImUpdatedBy() {
		return this.imUpdatedBy;
	}

	public void setImUpdatedBy(String imUpdatedBy) {
		this.imUpdatedBy = imUpdatedBy;
	}

	public Date getImUpdatedDate() {
		return this.imUpdatedDate;
	}

	public void setImUpdatedDate(Date imUpdatedDate) {
		this.imUpdatedDate = imUpdatedDate;
	}

	public String getImComment() {
		return this.imComment;
	}

	public void setImComment(String imComment) {
		this.imComment = imComment;
	}

	public Date getImCaptureTime() {
		return this.imCaptureTime;
	}

	public void setImCaptureTime(Date imCaptureTime) {
		this.imCaptureTime = imCaptureTime;
	}

	public Date getImCaptureDate() {
		return this.imCaptureDate;
	}

	public void setImCaptureDate(Date imCaptureDate) {
		this.imCaptureDate = imCaptureDate;
	}

	public String getImCameraMake() {
		return this.imCameraMake;
	}

	public void setImCameraMake(String imCameraMake) {
		this.imCameraMake = imCameraMake;
	}

	public String getImCameraModel() {
		return this.imCameraModel;
	}

	public void setImCameraModel(String imCameraModel) {
		this.imCameraModel = imCameraModel;
	}

	public Double getImFocal() {
		return this.imFocal;
	}

	public void setImFocal(Double imFocal) {
		this.imFocal = imFocal;
	}

	public Double getImAperature() {
		return this.imAperature;
	}

	public void setImAperature(Double imAperature) {
		this.imAperature = imAperature;
	}

	public Double getImExposure() {
		return this.imExposure;
	}

	public void setImExposure(Double imExposure) {
		this.imExposure = imExposure;
	}

	public String getImIso() {
		return this.imIso;
	}

	public void setImIso(String imIso) {
		this.imIso = imIso;
	}

}
