package competition.onedata.hibernate.reveng.pojo;

// Generated Jan 24, 2014 10:35:50 PM by Hibernate Tools 3.4.0.CR1

/**
 * RoadSectionSpeedId generated by hbm2java
 */
public class RoadSectionSpeedId implements java.io.Serializable {

	private int ssStartPointKey;
	private int ssEndPointKey;

	public RoadSectionSpeedId() {
	}

	public RoadSectionSpeedId(int ssStartPointKey, int ssEndPointKey) {
		this.ssStartPointKey = ssStartPointKey;
		this.ssEndPointKey = ssEndPointKey;
	}

	public int getSsStartPointKey() {
		return this.ssStartPointKey;
	}

	public void setSsStartPointKey(int ssStartPointKey) {
		this.ssStartPointKey = ssStartPointKey;
	}

	public int getSsEndPointKey() {
		return this.ssEndPointKey;
	}

	public void setSsEndPointKey(int ssEndPointKey) {
		this.ssEndPointKey = ssEndPointKey;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RoadSectionSpeedId))
			return false;
		RoadSectionSpeedId castOther = (RoadSectionSpeedId) other;

		return (this.getSsStartPointKey() == castOther.getSsStartPointKey())
				&& (this.getSsEndPointKey() == castOther.getSsEndPointKey());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSsStartPointKey();
		result = 37 * result + this.getSsEndPointKey();
		return result;
	}

}
