package competition.onedata.hibernate.reveng.pojo;

// Generated Jan 24, 2014 10:35:50 PM by Hibernate Tools 3.4.0.CR1

/**
 * RoadAccidentSectionId generated by hbm2java
 */
public class RoadAccidentSectionId implements java.io.Serializable {

	private int asAccidentKey;
	private int asSectionStartKey;
	private int asSectionEndKey;

	public RoadAccidentSectionId() {
	}

	public RoadAccidentSectionId(int asAccidentKey, int asSectionStartKey,
			int asSectionEndKey) {
		this.asAccidentKey = asAccidentKey;
		this.asSectionStartKey = asSectionStartKey;
		this.asSectionEndKey = asSectionEndKey;
	}

	public int getAsAccidentKey() {
		return this.asAccidentKey;
	}

	public void setAsAccidentKey(int asAccidentKey) {
		this.asAccidentKey = asAccidentKey;
	}

	public int getAsSectionStartKey() {
		return this.asSectionStartKey;
	}

	public void setAsSectionStartKey(int asSectionStartKey) {
		this.asSectionStartKey = asSectionStartKey;
	}

	public int getAsSectionEndKey() {
		return this.asSectionEndKey;
	}

	public void setAsSectionEndKey(int asSectionEndKey) {
		this.asSectionEndKey = asSectionEndKey;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RoadAccidentSectionId))
			return false;
		RoadAccidentSectionId castOther = (RoadAccidentSectionId) other;

		return (this.getAsAccidentKey() == castOther.getAsAccidentKey())
				&& (this.getAsSectionStartKey() == castOther
						.getAsSectionStartKey())
				&& (this.getAsSectionEndKey() == castOther.getAsSectionEndKey());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAsAccidentKey();
		result = 37 * result + this.getAsSectionStartKey();
		result = 37 * result + this.getAsSectionEndKey();
		return result;
	}

}
