package competition.onedata.hibernate.reveng.pojo;

// Generated Jan 24, 2014 10:35:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * RoadAccident generated by hbm2java
 */
public class RoadAccident implements java.io.Serializable {

	private Integer raAccidentKey;
	private Date raDateTime;
	private String raDetail;

	public RoadAccident() {
	}

	public RoadAccident(Date raDateTime, String raDetail) {
		this.raDateTime = raDateTime;
		this.raDetail = raDetail;
	}

	public Integer getRaAccidentKey() {
		return this.raAccidentKey;
	}

	public void setRaAccidentKey(Integer raAccidentKey) {
		this.raAccidentKey = raAccidentKey;
	}

	public Date getRaDateTime() {
		return this.raDateTime;
	}

	public void setRaDateTime(Date raDateTime) {
		this.raDateTime = raDateTime;
	}

	public String getRaDetail() {
		return this.raDetail;
	}

	public void setRaDetail(String raDetail) {
		this.raDetail = raDetail;
	}

}
