package competition.onedata.hibernate.reveng.pojo;

// Generated Jan 24, 2014 10:35:50 PM by Hibernate Tools 3.4.0.CR1

/**
 * RoadAccidentSection generated by hbm2java
 */
public class RoadAccidentSection implements java.io.Serializable {

	private RoadAccidentSectionId id;

	public RoadAccidentSection() {
	}

	public RoadAccidentSection(RoadAccidentSectionId id) {
		this.id = id;
	}

	public RoadAccidentSectionId getId() {
		return this.id;
	}

	public void setId(RoadAccidentSectionId id) {
		this.id = id;
	}

}
