package competition.onedata.hibernate.reveng.pojo;

// Generated Jan 24, 2014 10:35:50 PM by Hibernate Tools 3.4.0.CR1

import competition.onedata.hibernate.type.RoadChar;
import competition.onedata.hibernate.type.RoadRegionChar;

/**
 * RoadSection generated by hbm2java
 */
public class RoadSection implements java.io.Serializable {

	private RoadSectionId id;
	private double rsStartEast;
	private double rsStartNorth;
	private double rsEndEast;
	private double rsEndNorth;
	private RoadRegionChar rsRegion;
	private RoadChar rsType;

	public RoadSection() {
	}

	public RoadSection(RoadSectionId id, double rsStartEast,
			double rsStartNorth, double rsEndEast, double rsEndNorth,
			RoadRegionChar rsRegion, RoadChar rsType) {
		this.id = id;
		this.rsStartEast = rsStartEast;
		this.rsStartNorth = rsStartNorth;
		this.rsEndEast = rsEndEast;
		this.rsEndNorth = rsEndNorth;
		this.rsRegion = rsRegion;
		this.rsType = rsType;
	}

	public RoadSectionId getId() {
		return this.id;
	}

	public void setId(RoadSectionId id) {
		this.id = id;
	}

	public double getRsStartEast() {
		return this.rsStartEast;
	}

	public void setRsStartEast(double rsStartEast) {
		this.rsStartEast = rsStartEast;
	}

	public double getRsStartNorth() {
		return this.rsStartNorth;
	}

	public void setRsStartNorth(double rsStartNorth) {
		this.rsStartNorth = rsStartNorth;
	}

	public double getRsEndEast() {
		return this.rsEndEast;
	}

	public void setRsEndEast(double rsEndEast) {
		this.rsEndEast = rsEndEast;
	}

	public double getRsEndNorth() {
		return this.rsEndNorth;
	}

	public void setRsEndNorth(double rsEndNorth) {
		this.rsEndNorth = rsEndNorth;
	}

	public RoadRegionChar getRsRegion() {
		return this.rsRegion;
	}

	public void setRsRegion(RoadRegionChar rsRegion) {
		this.rsRegion = rsRegion;
	}

	public RoadChar getRsType() {
		return this.rsType;
	}

	public void setRsType(RoadChar rsType) {
		this.rsType = rsType;
	}

}
