package competition.onedata.hibernate.reveng.pojo;

// Generated Jan 24, 2014 10:35:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SuspendClasses generated by hbm2java
 */
public class SuspendClasses implements java.io.Serializable {

	private Integer scKey;
	private Date scDate;
	private String scDetail;

	public SuspendClasses() {
	}

	public SuspendClasses(Date scDate, String scDetail) {
		this.scDate = scDate;
		this.scDetail = scDetail;
	}

	public Integer getScKey() {
		return this.scKey;
	}

	public void setScKey(Integer scKey) {
		this.scKey = scKey;
	}

	public Date getScDate() {
		return this.scDate;
	}

	public void setScDate(Date scDate) {
		this.scDate = scDate;
	}

	public String getScDetail() {
		return this.scDetail;
	}

	public void setScDetail(String scDetail) {
		this.scDetail = scDetail;
	}

}
